### ISSUE TITLE
Error converting ROS2 bag to NuScenes

### ISSUE THREAD

**Issue by Zakhar02** [linklab-uva/rosbag2nuscenes#10]
```
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Error during open!
```
how can be reproduced: ```./rosbag2nuscenes ../../bag/ ../conf.yml /workspace/src/rosbag2nuscenes/NuScenes/ 8```
C++17

**Comment by Zakhar02** [comment]
I suppose the problem is in ```SensorDataWriter.cpp::25```, ```pcl::io::raw_open``` returns -1

**Comment by john-chrosniak** [comment]
Sorry for the delayed response! Could you paste the output of `ros2 bag info <path to bag>`?

**Comment by Zakhar02** [comment]
![image](https://github.com/user-attachments/assets/aa4f1436-5342-4d48-a150-f96d4eb9bce3)

**Comment by Zakhar02** [comment]
![image](https://github.com/user-attachments/assets/8653893a-1ead-4ec1-b38e-f6a09eb8c99a)

**Comment by Zakhar02** [comment]
Turned out it is throwing ```No plugin found providing serialization format 'cdr'.``` Error, as mentioned in https://github.com/linklab-uva/rosbag2nuscenes/issues/13

**Comment by Bungehurst** [comment]
> Turned out it is throwing `No plugin found providing serialization format 'cdr'.` Error, as mentioned in #13

This warning can be ignored. After checking the config file, I find the topic name of the dataset is not consistant with the 'mit.yaml'. When I change it to the right one, the program runs well.

**Comment by Bungehurst** [comment]
> Turned out it is throwing `No plugin found providing serialization format 'cdr'.` Error, as mentioned in #13

This warning can be ignored. After checking the config file, I find the topic name of the dataset is not consistant with the 'mit.yaml'. When I change it to the right one, the program runs well.

**Comment by Zakhar02** [comment]
That's right, the problem is database opens in READ_ONLY mode
![image](https://github.com/user-attachments/assets/b25e61a6-ab69-4006-ada8-955a812f8b95)

**Comment by john-chrosniak** [comment]
Opening with read only is fine since the library does not write back to the ROS bag. Could you include your `conf.yml` file?

**Comment by Zakhar02** [comment]
```
BAG_INFO:
  TEAM: Self.AI
  DESCRIPTION: SK
  ODOM_TOPIC: /reaper/odom
  TRACK: IMS
  URDF: urdf/mark3.urdf
SENSOR_INFO:
  LIDAR_FRONT:
    TOPIC: /bnk/top/points
    FRAME: robot_base
  # LIDAR_LEFT:
  #   TOPIC: /robosense/left/points
  #   FRAME: robot_base
  # LIDAR_RIGHT:
  #   TOPIC: /robosense/right/points
  #   FRAME: robot_base
  CAMERA_FRONT:
    TOPIC: /stereo/center/image_raw_unsync/compressed
    FRAME: robot_base
    CALIB: /stereo/center/camera_info_raw
```
